name             'sc_infra_dev'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures sc_infra'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'build-essential'
depends 'postgresql'
depends 'mongodb'
depends 'redisio'
depends 'ruby_build'
depends 'nodejs'
depends 'rvm'
depends 'rbenv'
depends 'imagemagick'
